---
name: module3_task3

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: '0 0 * * *' # Run at 00:00 UTC every day

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Run setup.sh
        run: ./setup.sh
        working-directory: module3_task3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          working-directory: module3_task3

      - name: Run make build
        run: make build
        working-directory: module3_task3
      - name: Run make run
        run: make run
        working-directory: module3_task3

      - name: Run make test
        run: make test
        working-directory: module3_task3

      - name: Run make stop
        run: make stop
        working-directory: module3_task3

      - name: Package application
        if: steps.test.outputs.exit_code == 0
        run: make package
        working-directory: module3_task3

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: 1.0.0
          files: |
            module3_task3/DEPLOY.md
            module3_task3/awesome-website.zip
          body_path: module3_task3/DEPLOY.mdA
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: my_gh_org/my_gh_repo

      - name: archive build
        if: ${{ success()}}
        uses: actions/upload-artifact@v3
        with:
          name: upload-package
          path: module3_task3/awesome-website.zip
