name: release-drafter
on:
  push:
    branches:
      - main
      - master
    tags:
      - "v*.*.*"
    release:
      - created
   
jobs:
  update_release_draft:
    runs-on: ubuntu-22.04
    steps:
      - name: Draft a new release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOPS }}
