---
name: module3_task1

on:
  push:
  schedule:
    - cron: '0 0 * * *' # Run at 00:00 UTC every day

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20' 

      - name: Run setup.sh
        run: |
         cd module3_task1
         ./setup.sh

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.42.1
          working-directory: module3_task1

      - name: Run make build
        run: |
         cd module3_task1
         make build

      - name: Run make run
        run: |
         cd module3_task1
         make run

      - name: Run make test
        run: |
         cd module3_task1
         make test

      - name: Run make stop
        run: |
         cd module3_task1
         make stop

      - name: Run make clear
        run: |
         cd module3_task1
         make clean
