name: Release Drafter
on:
  push:
    branches:
      - main
    tags:
      - '*'
  release:
    types:
      - created
jobs:
  update_release_draft:
    runs-on: ubuntu-22.04
    steps:
      - name: Draft a new release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
