---
name: module3_task0

on:
  push:
  schedule:
    - cron: '0 0 * * *' # Run at 00:00 UTC every day

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run make help
        run: |
          cd module3_task0
          make help
